[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "PORT"
value = "3001"

[build.nixpacksConfig]
build = """
npm ci --production
"""

[healthcheck]
path = "/health"
initialDelaySeconds = 30
timeoutSeconds = 10
intervalSeconds = 30
retries = 3

[networking]
externalPort = 3001
internalPort = 3001

[resources]
memory = "512Mi"
cpu = "500m"

[scaling]
minReplicas = 1
maxReplicas = 3
targetCPUPercent = 70
targetMemoryPercent = 80